### ISSUE TITLE
Consideration of replicate (Fold change calculation)

### ISSUE THREAD

**Issue by hmkim** [krassowski/drug-disease-profile-matching#1]
Hi, @krassowski 

I wonder this repo code consider a replication effect (e.g calculation of significance for case/control difference) on comparison of case/control expression values.

Thank you in advance!

Hyunmin

**Comment by krassowski** [comment]
Hi @hmkim, sorry for the delay in getting back to you - I ust have missed this. Yes, I did consider the significance of the effect size estimate for some of the "scoring functions", notably the functions based on gene sets. I hope it helps!
